{
 "title": "User Stats",
 "description": "Stats for individual users. Dashboard by Mijago",
 "time": { "from": "2023-04-01T09:44:03.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "Username",
    "query": "SHOW TAG VALUES WITH KEY = \"user_displayName\""
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commendation Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "totalScore" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Highest Equipped Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "user_profile_generic",
     "select": [
      [
       { "params": [ "light" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Guardian Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_profile_generic",
     "select": [
      [
       { "params": [ "currentGuardianRank" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Current" ], "type": "alias" }
      ],
      [
       { "params": [ "lifetimeHighestGuardianRank" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Lifetime Highest" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Playtime",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "secondsPlayed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / 60" ], "type": "math" },
       { "params": [ "Minutes Played" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvE" }
     ]
    }
   ]
  },
  {
   "title": "Orbs of Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "orbsGathered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Gathered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvE" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "orbsDropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Dropped" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvE" }
     ]
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Triumph Score",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_profile_records",
     "select": [
      [
       { "params": [ "lifetimeScore" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "activeScore" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Playtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_profile_generic",
     "select": [
      [
       { "params": [ "minutesPlayedTotal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*60" ], "type": "math" },
       { "params": [ "Lifetime" ], "type": "alias" }
      ],
      [
       { "params": [ "minutesPlayedThisSession" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*60" ], "type": "math" },
       { "params": [ "Last Session" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Season Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2808356364" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Orbs of Light",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "2h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "orbsDropped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Dropped" ], "type": "alias" }
      ],
      [
       { "params": [ "orbsGathered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Gathered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvE" }
     ]
    }
   ]
  },
  {
   "title": "Season Rank",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2808356364" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Orbs of Light",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "orbsDropped" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Dropped" ], "type": "alias" }
      ],
      [
       { "params": [ "orbsGathered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Gathered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvE" }
     ]
    }
   ]
  },
  { "title": "Kills", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Weekly Final Blows per Element",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1041413574" ], "type": "field" },
       { "params": [ "Arc" ], "type": "alias" }
      ],
      [
       { "params": [ "980916121" ], "type": "field" },
       { "params": [ "Solar" ], "type": "alias" }
      ],
      [
       { "params": [ "3286925104" ], "type": "field" },
       { "params": [ "Void" ], "type": "alias" }
      ],
      [
       { "params": [ "3399691711" ], "type": "field" },
       { "params": [ "Stasis" ], "type": "alias" }
      ],
      [
       { "params": [ "289019406" ], "type": "field" },
       { "params": [ "Strand" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Weekly Final Blows per Element",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 15 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1041413574" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Arc" ], "type": "alias" }
      ],
      [
       { "params": [ "980916121" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Solar" ], "type": "alias" }
      ],
      [
       { "params": [ "3286925104" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Void" ], "type": "alias" }
      ],
      [
       { "params": [ "3399691711" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Stasis" ], "type": "alias" }
      ],
      [
       { "params": [ "289019406" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Strand" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Seasonal Final Blows per Element",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "349633351" ], "type": "field" },
       { "params": [ "Arc" ], "type": "alias" }
      ],
      [
       { "params": [ "312507792" ], "type": "field" },
       { "params": [ "Solar" ], "type": "alias" }
      ],
      [
       { "params": [ "3099500251" ], "type": "field" },
       { "params": [ "Void" ], "type": "alias" }
      ],
      [
       { "params": [ "2526120300" ], "type": "field" },
       { "params": [ "Stasis" ], "type": "alias" }
      ],
      [
       { "params": [ "4142054589" ], "type": "field" },
       { "params": [ "Strand" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Seasonal Final Blows per Element",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "349633351" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Arc" ], "type": "alias" }
      ],
      [
       { "params": [ "312507792" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Solar" ], "type": "alias" }
      ],
      [
       { "params": [ "3099500251" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Void" ], "type": "alias" }
      ],
      [
       { "params": [ "2526120300" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Stasis" ], "type": "alias" }
      ],
      [
       { "params": [ "4142054589" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Strand" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Final Blows per Element Subclass Equipped",
   "type": "piechart",
   "description": "Display might be bugged",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1589465158" ], "type": "field" },
       { "params": [ "Gunslinger" ], "type": "alias" }
      ],
      [
       { "params": [ "1207645930" ], "type": "field" },
       { "params": [ "Sunbreaker" ], "type": "alias" }
      ],
      [
       { "params": [ "1414591655" ], "type": "field" },
       { "params": [ "Dawnblade" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1230686413" ], "type": "field" },
       { "params": [ "Arcstrider" ], "type": "alias" }
      ],
      [
       { "params": [ "4241711601" ], "type": "field" },
       { "params": [ "Striker" ], "type": "alias" }
      ],
      [
       { "params": [ "691593924" ], "type": "field" },
       { "params": [ "Stormcaller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2336777673" ], "type": "field" },
       { "params": [ "Nightstalker" ], "type": "alias" }
      ],
      [
       { "params": [ "3212243437" ], "type": "field" },
       { "params": [ "Sentinel" ], "type": "alias" }
      ],
      [
       { "params": [ "2536360546" ], "type": "field" },
       { "params": [ "Voidwalker" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4045407642" ], "type": "field" },
       { "params": [ "Revenant" ], "type": "alias" }
      ],
      [
       { "params": [ "1029275358" ], "type": "field" },
       { "params": [ "Behemoth" ], "type": "alias" }
      ],
      [
       { "params": [ "3875986497" ], "type": "field" },
       { "params": [ "Shadebinder" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3728422247" ], "type": "field" },
       { "params": [ "Threadrunner" ], "type": "alias" }
      ],
      [
       { "params": [ "588411275" ], "type": "field" },
       { "params": [ "Berserker" ], "type": "alias" }
      ],
      [
       { "params": [ "1086612732" ], "type": "field" },
       { "params": [ "Broodweaver" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Final Blows per Element Subclass Equipped",
   "type": "timeseries",
   "description": "Display might be bugged",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 23 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1589465158" ], "type": "field" },
       { "params": [ "Gunslinger" ], "type": "alias" }
      ],
      [
       { "params": [ "1207645930" ], "type": "field" },
       { "params": [ "Sunbreaker" ], "type": "alias" }
      ],
      [
       { "params": [ "1414591655" ], "type": "field" },
       { "params": [ "Dawnblade" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1230686413" ], "type": "field" },
       { "params": [ "Arcstrider" ], "type": "alias" }
      ],
      [
       { "params": [ "4241711601" ], "type": "field" },
       { "params": [ "Striker" ], "type": "alias" }
      ],
      [
       { "params": [ "691593924" ], "type": "field" },
       { "params": [ "Stormcaller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2336777673" ], "type": "field" },
       { "params": [ "Nightstalker" ], "type": "alias" }
      ],
      [
       { "params": [ "3212243437" ], "type": "field" },
       { "params": [ "Sentinel" ], "type": "alias" }
      ],
      [
       { "params": [ "2536360546" ], "type": "field" },
       { "params": [ "Voidwalker" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4045407642" ], "type": "field" },
       { "params": [ "Revenant" ], "type": "alias" }
      ],
      [
       { "params": [ "1029275358" ], "type": "field" },
       { "params": [ "Behemoth" ], "type": "alias" }
      ],
      [
       { "params": [ "3875986497" ], "type": "field" },
       { "params": [ "Shadebinder" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3728422247" ], "type": "field" },
       { "params": [ "Threadrunner" ], "type": "alias" }
      ],
      [
       { "params": [ "588411275" ], "type": "field" },
       { "params": [ "Berserker" ], "type": "alias" }
      ],
      [
       { "params": [ "1086612732" ], "type": "field" },
       { "params": [ "Broodweaver" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Final Blows per Subclass equipped",
   "type": "timeseries",
   "description": "Display might be bugged",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1589465158" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Gunslinger" ], "type": "alias" }
      ],
      [
       { "params": [ "1207645930" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sunbreaker" ], "type": "alias" }
      ],
      [
       { "params": [ "1414591655" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Dawnblade" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1230686413" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Arcstrider" ], "type": "alias" }
      ],
      [
       { "params": [ "4241711601" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Striker" ], "type": "alias" }
      ],
      [
       { "params": [ "691593924" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Stormcaller" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2336777673" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Nightstalker" ], "type": "alias" }
      ],
      [
       { "params": [ "3212243437" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Sentinel" ], "type": "alias" }
      ],
      [
       { "params": [ "2536360546" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Voidwalker" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4045407642" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Revenant" ], "type": "alias" }
      ],
      [
       { "params": [ "1029275358" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Behemoth" ], "type": "alias" }
      ],
      [
       { "params": [ "3875986497" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shadebinder" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3728422247" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Threadrunner" ], "type": "alias" }
      ],
      [
       { "params": [ "588411275" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Berserker" ], "type": "alias" }
      ],
      [
       { "params": [ "1086612732" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Broodweaver" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "Raids", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Raid Clears",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3766204132" ], "type": "field" },
       { "params": [ "Last Wish" ], "type": "alias" }
      ],
      [
       { "params": [ "1428773193" ], "type": "field" },
       { "params": [ "Deep Stone Crypt" ], "type": "alias" }
      ],
      [
       { "params": [ "1092085792" ], "type": "field" },
       { "params": [ "King's Fall" ], "type": "alias" }
      ],
      [
       { "params": [ "2207849635" ], "type": "field" },
       { "params": [ "Vault of Glass" ], "type": "alias" }
      ],
      [
       { "params": [ "1061853070" ], "type": "field" },
       { "params": [ "Garden of Salvation" ], "type": "alias" }
      ],
      [
       { "params": [ "586374027" ], "type": "field" },
       { "params": [ "Root of Nightmares" ], "type": "alias" }
      ],
      [
       { "params": [ "2669380142" ], "type": "field" },
       { "params": [ "Vow of the Disciple" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Raid Clear Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 32 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3766204132" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Last Wish" ], "type": "alias" }
      ],
      [
       { "params": [ "1428773193" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Deep Stone Crypt" ], "type": "alias" }
      ],
      [
       { "params": [ "1092085792" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "King's Fall" ], "type": "alias" }
      ],
      [
       { "params": [ "2207849635" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Vault of Glass" ], "type": "alias" }
      ],
      [
       { "params": [ "1061853070" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Garden of Salvation" ], "type": "alias" }
      ],
      [
       { "params": [ "586374027" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Root of Nightmares" ], "type": "alias" }
      ],
      [
       { "params": [ "2669380142" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Vow of the Disciple" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Raid Clears",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 32 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "2h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "3766204132" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Last Wish" ], "type": "alias" }
      ],
      [
       { "params": [ "1428773193" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Deep Stone Crypt" ], "type": "alias" }
      ],
      [
       { "params": [ "1092085792" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "King's Fall" ], "type": "alias" }
      ],
      [
       { "params": [ "2207849635" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Vault of Glass" ], "type": "alias" }
      ],
      [
       { "params": [ "1061853070" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Garden of Salvation" ], "type": "alias" }
      ],
      [
       { "params": [ "586374027" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Root of Nightmares" ], "type": "alias" }
      ],
      [
       { "params": [ "2669380142" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Vow of the Disciple" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "Dungeons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Dungeon Clears",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4013262262" ], "type": "field" },
       { "params": [ "Pit of Heresy" ], "type": "alias" }
      ],
      [
       { "params": [ "3724198973" ], "type": "field" },
       { "params": [ "Spire of the Watcher" ], "type": "alias" }
      ],
      [
       { "params": [ "1122975215" ], "type": "field" },
       { "params": [ "Duality" ], "type": "alias" }
      ],
      [
       { "params": [ "503493213" ], "type": "field" },
       { "params": [ "Prophecy" ], "type": "alias" }
      ],
      [
       { "params": [ "3685683083" ], "type": "field" },
       { "params": [ "Grasp of Avarice" ], "type": "alias" }
      ],
      [
       { "params": [ "1901292096" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shattered Throne" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Dungeon Clears",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 41 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4013262262" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Pit of Heresy" ], "type": "alias" }
      ],
      [
       { "params": [ "3724198973" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Spire of the Watcher" ], "type": "alias" }
      ],
      [
       { "params": [ "1122975215" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Duality" ], "type": "alias" }
      ],
      [
       { "params": [ "503493213" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Prophecy" ], "type": "alias" }
      ],
      [
       { "params": [ "3685683083" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Grasp of Avarice" ], "type": "alias" }
      ],
      [
       { "params": [ "1901292096" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Shattered Throne" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Dungeon Clears",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 41 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "2h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4013262262" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Pit of Heresy" ], "type": "alias" }
      ],
      [
       { "params": [ "3724198973" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Spire of the Watcher" ], "type": "alias" }
      ],
      [
       { "params": [ "1122975215" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Duality" ], "type": "alias" }
      ],
      [
       { "params": [ "503493213" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Prophecy" ], "type": "alias" }
      ],
      [
       { "params": [ "3685683083" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Grasp of Avarice" ], "type": "alias" }
      ],
      [
       { "params": [ "1901292096" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Shattered Throne" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "Commendations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Commendations per type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "2019871317" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Indispensable" ], "type": "alias" }
      ],
      [
       { "params": [ "354527503" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Selfless" ], "type": "alias" }
      ],
      [
       { "params": [ "3513056018" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Thoughtful" ], "type": "alias" }
      ],
      [
       { "params": [ "2506835299" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Patient and Considerate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "4209356036" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Playmaker" ], "type": "alias" }
      ],
      [
       { "params": [ "363818544" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Primeval Instinct" ], "type": "alias" }
      ],
      [
       { "params": [ "3575743922" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Heroic" ], "type": "alias" }
      ],
      [
       { "params": [ "2205006002" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Pacesetter" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "3872064891" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Perceptive" ], "type": "alias" }
      ],
      [
       { "params": [ "3970150545" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Knowledgeable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "3377580220" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Joy Bringer" ], "type": "alias" }
      ],
      [
       { "params": [ "3037314846" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Level-headed" ], "type": "alias" }
      ],
      [
       { "params": [ "3030493827" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Saint's Favorite" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Commendation Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 50 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "2019871317" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Indispensable" ], "type": "alias" }
      ],
      [
       { "params": [ "354527503" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Selfless" ], "type": "alias" }
      ],
      [
       { "params": [ "3513056018" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Thoughtful" ], "type": "alias" }
      ],
      [
       { "params": [ "2506835299" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Patient and Considerate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "4209356036" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Playmaker" ], "type": "alias" }
      ],
      [
       { "params": [ "363818544" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Primeval Instinct" ], "type": "alias" }
      ],
      [
       { "params": [ "3575743922" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Heroic" ], "type": "alias" }
      ],
      [
       { "params": [ "2205006002" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Pacesetter" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "3872064891" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Perceptive" ], "type": "alias" }
      ],
      [
       { "params": [ "3970150545" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Knowledgeable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_profile_commendations",
     "select": [
      [
       { "params": [ "3377580220" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Joy Bringer" ], "type": "alias" }
      ],
      [
       { "params": [ "3037314846" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Level-headed" ], "type": "alias" }
      ],
      [
       { "params": [ "3030493827" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Saint's Favorite" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  { "title": "PvP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Combat Rating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "combatRating" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "K/D" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Orbs of Light",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "orbsDropped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Dropped" ], "type": "alias" }
      ],
      [
       { "params": [ "orbsGathered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Gathered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Kills, Deaths, Assists, Suicides",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "kills" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Kills" ], "type": "alias" }
      ],
      [
       { "params": [ "assists" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Assists" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "suicides" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Suicides" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "K/D and KA/D",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "killsDeathsRatio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "K/D" ], "type": "alias" }
      ],
      [
       { "params": [ "killsDeathsAssists" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "KA/D" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Kills, Deaths, Assists",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 57 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "kills" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Kills" ], "type": "alias" }
      ],
      [
       { "params": [ "assists" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Assists" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Activity Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "activitiesEntered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Entered" ], "type": "alias" }
      ],
      [
       { "params": [ "activitiesWon" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Won" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Kill Distance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "averageKillDistance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Average" ], "type": "alias" }
      ],
      [
       { "params": [ "longestKillDistance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Longest" ], "type": "alias" }
      ],
      [
       { "params": [ "totalKillDistance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Ratios",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "killsDeathsRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "K/D" ], "type": "alias" }
      ],
      [
       { "params": [ "killsDeathsAssists" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "KA/D" ], "type": "alias" }
      ],
      [
       { "params": [ "winLossRatio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Win/Loss" ], "type": "alias" }
      ],
      [
       { "params": [ "efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Efficiency" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Most Precision Kills in a Match",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "mostPrecisionKills" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "K/D" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Most Kills per Match",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "bestSingleGameKills" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Best Single Game Kills" ], "type": "alias" }
      ],
      [
       { "params": [ "bestSingleGameScore" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Best Single Game Score" ], "type": "alias" }
      ],
      [
       { "params": [ "mostPrecisionKills" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Best Single Game Prec. Kills" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Weapon Type Kills",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "weaponKillsAutoRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Auto Rifle" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsBeamRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Beam Rifle" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsBow" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Bow" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsFusionRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Fusion Rifle" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsGlaive" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Glaive" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsGrenade" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Grenade" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsGrenadeLauncher" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Grenade Launcher" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsHandCannon" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Hand Cannon" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsMachineGun" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Machine Gun" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsMelee" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Melee" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsPulseRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Pulse Rifle" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsRelic" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Relic" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsRocketLauncher" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Rocket Launcher" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsScoutRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Scout Rifle" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsShotgun" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Shotgun" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsSideArm" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Side Arm" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsSniper" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sniper" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsSubmachinegun" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "SMG" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsSuper" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Super" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsSword" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sword" ], "type": "alias" }
      ],
      [
       { "params": [ "weaponKillsTraceRifle" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Trace Rifle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Changes in K/D",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "3h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "killsDeathsRatio" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "K/D" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  {
   "title": "Kills, Assists and Deaths",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 66 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_historical_stats_merged",
     "select": [
      [
       { "params": [ "kills" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Kills" ], "type": "alias" }
      ],
      [
       { "params": [ "assists" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Assists" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" },
      { "condition": "AND", "key": "category", "operator": "=", "value": "allPvP" }
     ]
    }
   ]
  },
  { "title": "Gambit (eww)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Matches Won",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4262810434" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Motes Banked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1842945649" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Blockers Defeated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1215096138" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Primevals Defeated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "4144258556" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Invader Defeated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "2842803544" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Gambit Rank Resets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "236484886" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  },
  {
   "title": "Gambit Title Gildings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "6h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "user_character_metrics",
     "select": [
      [
       { "params": [ "1492765514" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "user_displayName", "operator": "=~", "value": "/^$username$/" }
     ]
    }
   ]
  }
 ]
}